### ISSUE TITLE
errors on the upper status pane.

### ISSUE THREAD

**Issue by nerd190** [t-e-l/tel#5]
**Problem description**

errors every few seconds on upper screen.
**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: stable
* Android OS version: 10.0 - lineage OS
* Device model: OnePlus 5T

```bash
No notifications availible - check termux-api permissions         Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.tel/status/04-storage.py", line 13, in <module>                                                                   sd_card_path = os.environ['PATH_TO_SD']
  File "/data/data/com.termux/files/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None                                           KeyError: 'PATH_TO_SD'
/data/data/com.termux/files/home/.tel/scripts/helpers.sh: line 14: 1: parameter null or not set
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.tel/status/06-notification.py", line 11, in <module>
    notification_display_type = os.environ['NOTIFICATIONS_DISPLAY_TYPE']
  File "/data/data/com.termux/files/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'NOTIFICATIONS_DISPLAY_TYPE'
/data/data/com.termux/files/home/.tel/scripts/helpers.sh: line 14: 1: parameter null or not set
```

great app! thank you!!

**Comment by SealedJoy** [comment]
Fixed in coming update :+1:

**Comment by v1nc** [comment]
Fixed with the latest updated.
